In [43]:
from pymongo import MongoClient
import pandas as pd

In [44]:
client = MongoClient("mongodb://localhost:27017/")

In [45]:
def upload_target(filename):
    client = MongoClient("mongodb://localhost:27017/")
    collection = client.get_database("prediction_service").get_collection("data")
    with open(filename) as f_target:
        for line in f_target.readlines():
            row = line.split(",")
            collection.update_one({"id": row[0]}, {"$set": {"target": float(row[1])}})
    client.close()

upload_target("target.csv")

In [46]:
data = client.get_database("prediction_service").get_collection("data").find()
df = pd.DataFrame(list(data))
df.tail()

,_id,male,age,education,currentsmoker,cigsperday,bpmeds,prevalentstroke,prevalenthyp,diabetes,totchol,sysbp,diabp,bmi,heartrate,glucose,prediction,tenyearchd,id
549,62f8793a601a2daaace7b595,1,53,1.0,1,20.0,0.0,0,0,0,188.0,138.0,89.0,18.23,60.0,75.0,0.218739,0.0,9578fd7d-819b-4f7b-80bb-840cc7ea025c
550,62f87b9e477d6b2db704f1d3,1,53,1.0,0,0.0,0.0,0,0,0,220.0,127.0,76.0,24.27,75.0,74.0,0.189975,0.0,a2806726-8af3-46a4-bbc0-c98e276ce0b1
551,62f87ba0477d6b2db704f1d4,0,44,1.0,0,0.0,0.0,0,0,0,195.0,118.0,86.0,23.09,70.0,75.0,0.092015,0.0,fd119ee3-39ca-4d91-b88a-f990d41d5953
552,62f87ba3477d6b2db704f1d5,0,44,4.0,0,0.0,0.0,0,0,0,205.0,109.0,73.0,17.48,75.0,57.0,0.092015,0.0,347ec6c6-7ca2-4e18-80b0-c485014abc00
553,62f87ba5477d6b2db704f1d6,0,66,1.0,0,0.0,0.0,1,1,0,278.0,187.0,88.0,40.52,90.0,84.0,0.223586,1.0,2b42898a-aa73-4f56-a62f-4e4264b21b23